"""
Treuno — Model-Execute
====================

Every code block generated by Treuno is automatically extracted and run
inside a Docker container with the gVisor secure runtime (runsc).

Security guarantees:
  - gVisor intercepts all syscalls → kernel attack surface eliminated
  - Network disabled (--network=none)
  - Memory capped at 256 MB per container
  - CPU quota enforced (0.5 CPU)
  - Filesystem is ephemeral (tmpfs), nothing persists
  - Hard 5-second execution timeout

Supported runtimes:
  Python  3.12   │  treuno/sandbox-python:3.12
  Node    20     │  treuno/sandbox-node:20
  Go      1.22   │  treuno/sandbox-go:1.22
  Rust    stable │  treuno/sandbox-rust:stable
  Java    21     │  treuno/sandbox-java:21
  GCC     14     │  treuno/sandbox-gcc:14      (C and C++)
  Ruby    3.3    │  treuno/sandbox-ruby:3.3
  PHP     8.3    │  treuno/sandbox-php:8.3
  Kotlin  JVM    │  treuno/sandbox-kotlin:jvm
  Swift   5.10   │  treuno/sandbox-swift:5.10
  Bash           │  treuno/sandbox-bash:latest

Self-correction loop:
  On failure: stdout + stderr → appended to prompt → model retries (max 3)
  After 3 failures: response intercepted by Model-Verify; never shown as solution.
"""

from __future__ import annotations

import os
import re
import time
import shlex
import logging
import tempfile
import subprocess
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)

# ── Supported sandbox images ──────────────────────────────────────────────────
SANDBOX_IMAGES = {
    "python":     "python:3.12-slim",
    "py":         "python:3.12-slim",
    "javascript": "node:20-slim",
    "js":         "node:20-slim",
    "node":       "node:20-slim",
    "typescript": "node:20-slim",
    "ts":         "node:20-slim",
    "go":         "golang:1.22-alpine",
    "rust":       "rust:slim",
    "java":       "eclipse-temurin:21-jdk-alpine",
    "c":          "gcc:14",
    "cpp":        "gcc:14",
    "c++":        "gcc:14",
    "ruby":       "ruby:3.3-slim",
    "php":        "php:8.3-cli-alpine",
    "kotlin":     "zenika/kotlin:latest",
    "swift":      "swift:5.10-slim",
    "bash":       "bash:latest",
    "sh":         "bash:latest",
}

# Per-language run commands inside the container
CONTAINER_RUN_CMDS = {
    "python":     "python /code/main.py",
    "javascript": "node /code/main.js",
    "typescript": "ts-node /code/main.ts",
    "go":         "go run /code/main.go",
    "rust":       "sh -c 'rustc /code/main.rs -o /tmp/main && /tmp/main'",
    "java":       "sh -c 'javac /code/Main.java -d /tmp && java -cp /tmp Main'",
    "c":          "sh -c 'gcc /code/main.c -o /tmp/main && /tmp/main'",
    "cpp":        "sh -c 'g++ /code/main.cpp -o /tmp/main && /tmp/main'",
    "ruby":       "ruby /code/main.rb",
    "php":        "php /code/main.php",
    "kotlin":     "kotlinc-jvm -script /code/main.kts",
    "swift":      "swift /code/main.swift",
    "bash":       "bash /code/main.sh",
}

# File extensions for temp source files
FILE_EXTENSIONS = {
    "python": ".py", "javascript": ".js", "typescript": ".ts",
    "go": ".go", "rust": ".rs", "java": ".java",
    "c": ".c", "cpp": ".cpp", "ruby": ".rb",
    "php": ".php", "kotlin": ".kts", "swift": ".swift", "bash": ".sh",
}

# Aliases
for _alias, _canonical in [
    ("py", "python"), ("js", "javascript"), ("ts", "typescript"),
    ("c++", "cpp"), ("sh", "bash"), ("node", "javascript"),
]:
    CONTAINER_RUN_CMDS[_alias] = CONTAINER_RUN_CMDS[_canonical]
    FILE_EXTENSIONS[_alias] = FILE_EXTENSIONS[_canonical]


@dataclass
class ExecutionResult:
    language: str
    code: str
    stdout: str
    stderr: str
    exit_code: int
    elapsed_seconds: float
    timed_out: bool = False
    docker_available: bool = True
    error_message: str = ""

    @property
    def success(self) -> bool:
        return self.exit_code == 0 and not self.timed_out

    @property
    def short_error(self) -> str:
        """Concise error for model feedback — last 5 lines of stderr."""
        if self.timed_out:
            return f"TimeoutError: execution exceeded 5 seconds."
        lines = (self.stderr or "").strip().splitlines()
        return "\n".join(lines[-5:]) if lines else ""

    def feedback_context(self) -> str:
        """Format error as model re-prompt context."""
        lines = [
            f"Your {self.language} code failed to execute.",
            f"```{self.language}\n{self.code}\n```",
            f"Error:\n{self.short_error}",
            "Please fix the code.",
        ]
        return "\n".join(lines)


class ModelExecute:
    """
    Model-Execute: Docker + gVisor secure code sandbox.

    Falls back to subprocess if Docker is unavailable (dev environments).
    Uses gVisor 'runsc' runtime for production; plain 'runc' for dev.
    """

    TIMEOUT_SECONDS = 5          # Hard limit per spec
    MAX_OUTPUT_BYTES = 65_536    # 64 KB — prevent memory bombs
    MEMORY_LIMIT = "256m"
    CPU_LIMIT = "0.5"

    def __init__(
        self,
        use_gvisor: bool = True,
        fallback_to_subprocess: bool = True,
    ):
        self.use_gvisor = use_gvisor
        self.fallback_to_subprocess = fallback_to_subprocess
        self._docker_available: Optional[bool] = None

    def run(
        self,
        code: str,
        language: str,
        stdin: Optional[str] = None,
    ) -> ExecutionResult:
        """
        Execute code block in isolated Docker+gVisor container.

        Args:
            code:     Source code string
            language: Language identifier (e.g. "python", "go", "rust")
            stdin:    Optional stdin piped to the program

        Returns:
            ExecutionResult with stdout, stderr, exit_code, elapsed_seconds
        """
        lang = language.lower().strip()
        if self._is_docker_available():
            return self._docker_run(code, lang, stdin)
        elif self.fallback_to_subprocess:
            logger.warning("Docker unavailable — falling back to subprocess sandbox.")
            return self._subprocess_run(code, lang, stdin)
        else:
            return ExecutionResult(
                language=lang, code=code, stdout="", stderr="Docker not available.",
                exit_code=1, elapsed_seconds=0.0, docker_available=False,
            )

    # ── Docker execution ──────────────────────────────────────────────────────

    def _docker_run(self, code: str, lang: str, stdin: Optional[str]) -> ExecutionResult:
        image = SANDBOX_IMAGES.get(lang)
        if not image:
            return ExecutionResult(
                language=lang, code=code, stdout="",
                stderr=f"Unsupported language: {lang}",
                exit_code=1, elapsed_seconds=0.0,
            )

        ext = FILE_EXTENSIONS.get(lang, ".txt")
        run_cmd = CONTAINER_RUN_CMDS.get(lang, f"cat /code/main{ext}")

        # Java special case: class must match filename
        if lang == "java":
            ext = ".java"
            run_cmd = "sh -c 'javac /code/Main.java -d /tmp && java -cp /tmp Main'"

        # Write code to temp file
        with tempfile.NamedTemporaryFile(
            suffix=ext,
            prefix="main" if lang != "java" else "Main",
            delete=False,
            mode="w",
            encoding="utf-8",
        ) as f:
            f.write(code)
            code_path = f.name

        runtime_flag = "--runtime=runsc" if self.use_gvisor else ""

        docker_cmd = [
            "docker", "run", "--rm",
            *(runtime_flag.split() if runtime_flag else []),
            "--network=none",
            f"--memory={self.MEMORY_LIMIT}",
            f"--cpus={self.CPU_LIMIT}",
            "--read-only",
            "--tmpfs=/tmp:size=64m",
            "-v", f"{code_path}:/code/main{ext}:ro",
            "--security-opt=no-new-privileges",
            image,
            "sh", "-c", run_cmd,
        ]

        t0 = time.perf_counter()
        try:
            proc = subprocess.run(
                docker_cmd,
                input=stdin,
                capture_output=True,
                text=True,
                timeout=self.TIMEOUT_SECONDS + 2,   # +2s for Docker startup
            )
            elapsed = time.perf_counter() - t0
            return ExecutionResult(
                language=lang,
                code=code,
                stdout=proc.stdout[:self.MAX_OUTPUT_BYTES],
                stderr=proc.stderr[:self.MAX_OUTPUT_BYTES],
                exit_code=proc.returncode,
                elapsed_seconds=elapsed,
                docker_available=True,
            )
        except subprocess.TimeoutExpired:
            elapsed = time.perf_counter() - t0
            return ExecutionResult(
                language=lang, code=code, stdout="",
                stderr=f"Execution timed out after {self.TIMEOUT_SECONDS}s.",
                exit_code=1, elapsed_seconds=elapsed,
                timed_out=True, docker_available=True,
            )
        except FileNotFoundError:
            self._docker_available = False
            return self._subprocess_run(code, lang, stdin)
        finally:
            try:
                os.unlink(code_path)
            except OSError:
                pass

    # ── Subprocess fallback ───────────────────────────────────────────────────

    def _subprocess_run(self, code: str, lang: str, stdin: Optional[str]) -> ExecutionResult:
        """
        Pure subprocess sandbox — no Docker isolation.
        Used in dev environments where Docker is not running.
        """
        from sandbox.executor import CodeExecutor
        executor = CodeExecutor(default_timeout=self.TIMEOUT_SECONDS)
        raw = executor.run(code, lang, timeout=self.TIMEOUT_SECONDS, stdin=stdin)
        return ExecutionResult(
            language=raw.language,
            code=raw.code,
            stdout=raw.stdout,
            stderr=raw.stderr,
            exit_code=raw.exit_code,
            elapsed_seconds=raw.elapsed_seconds,
            timed_out=raw.timed_out,
            docker_available=False,
        )

    # ── Docker availability check ─────────────────────────────────────────────

    def _is_docker_available(self) -> bool:
        if self._docker_available is not None:
            return self._docker_available
        try:
            result = subprocess.run(
                ["docker", "info"],
                capture_output=True,
                timeout=3,
            )
            self._docker_available = result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self._docker_available = False
        if not self._docker_available:
            logger.info("Docker not available — subprocess fallback active.")
        return self._docker_available

    # ── Code extraction ───────────────────────────────────────────────────────

    @staticmethod
    def extract_code_blocks(text: str) -> list[tuple[str, str]]:
        """
        Extract all code blocks from markdown model output.
        Returns list of (language, code) tuples.
        """
        pattern = r"```(\w+)?\s*\n(.*?)```"
        matches = re.findall(pattern, text, re.DOTALL)
        return [(lang.lower() or "python", code.strip()) for lang, code in matches]

    def __repr__(self) -> str:
        runtime = "gVisor+Docker" if self.use_gvisor else "Docker"
        if not self._is_docker_available():
            runtime = "subprocess (fallback)"
        return f"ModelExecute(runtime={runtime}, timeout={self.TIMEOUT_SECONDS}s)"
