"""
Treuno 125M — Data Pipeline
Quality-filtered code corpus collection for training.

Quality filter cascade (9 stages, matching Treuno-1B spec):
  1. Language detection — discard if not target language
  2. File size — 100 bytes < file < 1 MB
  3. Line length — avg < 100 chars, max < 1000 chars
  4. Non-ASCII ratio — < 20%
  5. Alpha ratio — > 10% alphabetic characters
  6. Auto-generated detection — skip files with autogen headers
  7. Duplication — skip exact hash duplicates
  8. Token length — 64 < tokens < 8192 (fits context window)
  9. StarEncoder quality classifier — score > 0.5 (optional, skip if slow)

Usage:
    python scripts/data_pipeline.py --output-dir d:/MODEL/data/raw
"""

import os
import sys
import json
import time
import hashlib
import argparse
import logging
from pathlib import Path
from typing import Iterator, Dict, Any, Set

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


# ── Language weights (training data mix) ─────────────────────────────────────
LANGUAGE_WEIGHTS = {
    "python":     0.25,
    "javascript": 0.15,
    "typescript": 0.10,
    "rust":       0.08,
    "go":         0.08,
    "cpp":        0.07,
    "java":       0.07,
    "c":          0.05,
    "bash":       0.05,
    "ruby":       0.03,
    "php":        0.03,
    "swift":      0.02,
    "kotlin":     0.02,
}

AUTOGEN_MARKERS = [
    "auto-generated", "autogenerated", "do not edit",
    "generated by", "this file was generated",
    "!!!!! do not modify",
]


class DataPipeline:
    """Code corpus quality filter pipeline."""

    def __init__(self, output_dir: str, max_files: int = 0):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.max_files = max_files
        self._seen_hashes: Set[str] = set()
        self.stats = {
            "total": 0, "passed": 0,
            **{f"failed_stage_{i}": 0 for i in range(1, 10)}
        }

    def filter(self, item: Dict[str, Any]) -> bool:
        """Run all 9 quality filter stages. Returns True if item passes."""
        content = item.get("content", "") or item.get("text", "")
        self.stats["total"] += 1

        # Stage 1: Language check
        lang = item.get("language", item.get("lang", "")).lower()
        if lang not in LANGUAGE_WEIGHTS:
            self.stats["failed_stage_1"] += 1
            return False

        # Stage 2: File size
        size = len(content.encode("utf-8"))
        if size < 100 or size > 1_000_000:
            self.stats["failed_stage_2"] += 1
            return False

        # Stage 3: Line length
        lines = content.splitlines()
        if not lines:
            self.stats["failed_stage_3"] += 1
            return False
        avg_len = sum(len(l) for l in lines) / len(lines)
        max_len = max(len(l) for l in lines)
        if avg_len > 100 or max_len > 1000:
            self.stats["failed_stage_3"] += 1
            return False

        # Stage 4: Non-ASCII ratio
        non_ascii = sum(1 for c in content if ord(c) > 127)
        if len(content) > 0 and non_ascii / len(content) > 0.20:
            self.stats["failed_stage_4"] += 1
            return False

        # Stage 5: Alpha ratio
        alpha = sum(1 for c in content if c.isalpha())
        if len(content) > 0 and alpha / len(content) < 0.10:
            self.stats["failed_stage_5"] += 1
            return False

        # Stage 6: Auto-generated detection
        head = content[:500].lower()
        if any(marker in head for marker in AUTOGEN_MARKERS):
            self.stats["failed_stage_6"] += 1
            return False

        # Stage 7: Deduplication (exact hash)
        h = hashlib.md5(content.encode("utf-8")).hexdigest()
        if h in self._seen_hashes:
            self.stats["failed_stage_7"] += 1
            return False
        self._seen_hashes.add(h)

        # Stage 8: Token length (rough estimate: ~3.5 chars/token)
        est_tokens = len(content) / 3.5
        if est_tokens < 64 or est_tokens > 8192:
            self.stats["failed_stage_8"] += 1
            return False

        self.stats["passed"] += 1
        return True

    def process_jsonl(self, input_path: str, lang_override: str = None) -> int:
        """Process a JSONL file through the filter pipeline."""
        out_path = self.output_dir / f"{Path(input_path).stem}_filtered.jsonl"
        written = 0
        with open(input_path, encoding="utf-8") as fin, \
             open(out_path, "w", encoding="utf-8") as fout:
            for line in fin:
                if self.max_files and written >= self.max_files:
                    break
                try:
                    item = json.loads(line.strip())
                except json.JSONDecodeError:
                    continue
                if lang_override:
                    item["language"] = lang_override
                if self.filter(item):
                    fout.write(json.dumps(item, ensure_ascii=False) + "\n")
                    written += 1
        logger.info(f"Filtered {input_path} → {written} examples written.")
        return written

    def print_stats(self):
        total = self.stats["total"]
        passed = self.stats["passed"]
        rate = 100 * passed / total if total > 0 else 0
        print(f"\n{'='*50}")
        print(f"  Data Pipeline Stats")
        print(f"{'='*50}")
        print(f"  Total processed:   {total:>10,}")
        print(f"  Passed:            {passed:>10,}  ({rate:.1f}%)")
        print(f"{'─'*50}")
        for i in range(1, 10):
            n = self.stats.get(f"failed_stage_{i}", 0)
            if n > 0:
                print(f"  Failed stage {i}:      {n:>10,}")
        print(f"{'='*50}\n")


def main():
    p = argparse.ArgumentParser(description="Treuno data pipeline")
    p.add_argument("--input", help="JSONL input file")
    p.add_argument("--output-dir", default="d:/MODEL/data/raw")
    p.add_argument("--language", default=None, help="Override language field")
    p.add_argument("--max-files", type=int, default=0, help="0 = no limit")
    args = p.parse_args()

    pipeline = DataPipeline(args.output_dir, max_files=args.max_files)
    if args.input:
        pipeline.process_jsonl(args.input, lang_override=args.language)
    else:
        logger.info("No --input provided. Running pipeline in demo mode.")
        demo_items = [
            {"content": "def hello():\n    print('Hello, world!')\n", "language": "python"},
            {"content": "auto-generated — do not edit\n" + "x" * 200, "language": "python"},
            {"content": "a" * 2_000_000, "language": "python"},  # too large
        ]
        for item in demo_items:
            result = pipeline.filter(item)
            print(f"  {'✅' if result else '❌'} {item['content'][:40]!r}...")

    pipeline.print_stats()


if __name__ == "__main__":
    main()
